<?php

namespace mn\hw4\controllers;

require_once 'Controller.php';

use mn\hw4\models\codesModel;
use mn\hw4\models\sheetModel;
use mn\hw4\views\editView;
use mn\hw4\views\readView;

class apiController extends Controller {
    public function __construct($logger, $type) {
        parent::__construct();
        switch($type){
            case "edit":
                $this->view = new editView($logger,"webLayout");
                break;
            case "read":
                $this->view = new readView($logger, "webLayout");
                break;
        }
    }
    public function index(){
        if(!isset($this->model['sheet'])){
            $this->model['sheet'] = new sheetModel();
            $this->model['code'] = new codesModel();

            // ** NEED TO SANITIZE **
            $data['name'] = $_REQUEST['arg1'];
            // First check if input is hash and exists inside our database
            // If so, check what type of code it is and select appropriate view.
            if($this->model['code']->existsHash($data['name'])){
                $id = $this->model['code']->getID($data['name']);
                // Fetch sheet name to display and then get codes
                $data['name'] = $this->model['sheet']->getName($id);
                $data['sheetCodes'] = $this->model['code']->select($id);
            }
            // If a name is given instead of a hash code
            else {
                $data['sheet'] = $this->model['sheet']->select($data['name']);
                $data['sheetData'] = $this->model['sheet']->selectData($data['name']);
                // Name doesn't exist in database
                if (empty($data['sheet'])) {
                    //insert new sheet into database
                    $data['sheetData'] = json_encode([["", ""],["", ""]]);
                    $this->model['sheet']->insert($data);
                    //fetch the sheet id and hash generated by SQL database
                    $data['id'] = $this->model['sheet']->select($data['name']);
                    //use that sheet to insert into sheet_codes and return the ID we used
                    $this->model['code']->insert($data);
                    //select the 3 codes to send to our view
                    $data['sheetCodes'] = $this->model['code']->select($data['id']);
                } else {
                    //use that sheet to insert into sheet_codes and return the ID we used
                    $id = $this->model['sheet']->select($data['name']);
                    //select the 3 codes to send to our view
                    $data['sheetCodes'] = $this->model['code']->select($id);
                }
            }
            $this->view->display($data);
        }
    }
}