<?php

namespace mn\hw4\controllers;

require_once 'Controller.php';

use mn\hw4\models\sheetModel;
use mn\hw4\views\editView;
use mn\hw4\views\readView;

class sheetController extends Controller {
    public function __construct($logger, $type) {
        parent::__construct();
        switch($type){
            case "edit":
                $this->view = new editView($logger,"webLayout");
                break;
            case "read":
                $this->view = new readView($logger, "webLayout");
                break;
        }
    }

    public function index(){
        $data['sheetName'] = $_REQUEST['arg1'];
        $data['hash'] = substr(hash("sha256", $data['sheetName']), 0, 8);

        if(!isset($this->model['sheet'])){
            $this->model['sheet'] = new sheetModel();
            $data['sheet'] = $this->model['sheet']->select($data['sheetName']);
            if(empty($data['sheet'])){
                //insert new sheet into database
                $this->model['sheet']->insert($data);
                //fetch the sheet id and hash generated by SQL database
                $data['sheet'] = $this->model['sheet']->select($data['sheetName']);
                //use that sheet to insert into sheet_codes and return the ID we used
                $id = $this->model['sheet']->insertCodes($data['sheet']);
                //select the 3 codes to send to our view
                $data['sheetCodes'] = $this->model['sheet']->selectCodes($id);
                print_r($data['sheetCodes']);
            }
        }
        $this->view->display($data);
    }
}